### ISSUE TITLE
Hopac dependency

### ISSUE THREAD

**Issue by isaacabraham** [haf/Http.fs#110]
Sorry for coming late to the party here (and for what is essentially a "why did you do this" post) but - what's the rationale behind having a dependency on Hopac in HTTP.fs? One of the things I liked the most about it was that it was a tiny library with basically zero dependencies. At worst it used async workflows which are native to F# anyway, and had built-in functions for synchronous calling. Now you need to open up Hopac and see `job { }` stuff floating around.

Was this _really_ necessary?

**Comment by object** [comment]
That's an interesting question. I also wonder if use Http.fs with Hopac is justified in our scenario. We started using Http.fs (switching from JSON Type Provider AsyncLoad and Request calls) as a nice DSL around HttpClient and HTTP low-level details. Then it was upgraded to version 3 that uses Hopac Jobs and suddenly it's no longer a wrapper and we are no longer in control, especially when it comes to threading and tasks. Actually I wish Http.fs was a hybrid: using Hopac for more complex scenarios and still offering a DSL wrapper around HttpClient for straightforward usage.

**Comment by haf** [comment]
@isaacabraham No it wasn't required, but we do a lot of Hopac things at qvitoo, and constantly converting between async and Hopac was causing friction and sometimes bugs to pop up. I also branched off a separate stable release branch without Hopac, before doing the major upgrade.

I've worked with Hopac for about one and a half years now and I can honestly say that it rocks. It's _really_ easy to write multi-threaded **correct** code now – once you get over the admittedly large learning hump.

To address @object's concerns, while I'm writing this; it's still just a wrapper, but with a different output monad - job instead of async.

Another reason that I moved to Hopac was that it will allow me to implement a high-performance pipelined HTTP request library using TCP sockets – and therefore move beyond the 'wrapping C#' stuff that it's been before. I want to consume stable NuGets – functionality wise they should never throw exceptions or have bugs in them, and this is on path towards that.

Finally the normal OSS footnote applies if you want a change to a library, PRs are welcome. I've started the migration towards a richer API and my time is very limited. So I tweeted and PR-ed and asked people like yourself to comment, but noone did. So I went ahead with the change and made it better for my own usage. Now that you participate in a discussion about it, we can start addressing your points.

From a dependency perspective;
1. Hopac as the output monad
2. Hopac as a dll on disk.

For 1 I fully understand your concerns; how about I add async variants of the functions? Does that solve point 1 for you?

For 2, perhaps it's OK to have another DLL on disk, when you're not even using it actively and if it doesn't figure in your API?

**Comment by object** [comment]
Thank you for a comprehensive and reasonable explanation. I only started using Http.fs about a couple of months ago when I was looking for a decent F# DSL to cover my HTTP needs. I've found some samples and blog posts that appreciated Http.fs, and all of them were using previous version of the library that wasn't based on Hopac. Only after I obtained latest Nuget packages I realized that major changes had been made. So I was late to the train to give any feedback, moreover at first I didn't feel myself qualified for the feedback. Only after a couple of PRs I feel myself more comfortable with the library internals.
Henrik you obviously had very good reasons for making this choice. It's just that it looks like a lot of devs looked at Http.fs like an F# HTTP API and wanted it to fit the places they were using HttpClient and WebRequest. For many it's a question about choosing between a simple wrapper and a manager that takes control of thread control. Just to give you an example: we are using Akka.NET with F# API. Actor model and Hopac Jobs are alternatives to each other. It doesn't make much sense for us to perform HTTP calls in other manner than technically running them as simple WebRequests from inside actors. It's easy to use Jobs, I just call run and getResponse but even if it's tiny it's an extra complexity and extra dependency that needs to be justified.
You are absolutely right that anyone having reasonable arguments on this matter should take an initiative and send you PR. As you know, I did it for small fixes, but this is a big design change and I don't have constructive ideas about how the new design could look like. But I will of course think about it, I need to understand more of Hopac.

**Comment by isaacabraham** [comment]
@haf I absolutely understand the reasons you're giving for including Hopac - and I don't want this to be an async vs hopac discussion either - I understand that they aren't the same thing.

I guess from my point of view it's just about (as @object mentions) that I liked Http.fs as a lightweight library that acted as a simple wrapper around HTTP client, nothing more. With the addition of Hopac, it's not just the need to reference an extra DLL (two actually) but also to understand how to do the equivalent of `RunSynchronously` on Hopac (which is this `run` function that's (I think?) auto-opened in a module in the Hopac namespace).

Some ideas: -
1. Add a `run` function into the main Http.fs namespace that just delegates to the Hopac one - at least then this somewhat stops the user having to know about it (although you're still going to see `Job` everywhere).
2. Add synchronous (very important to me as it's useful for scripting / exploration when asynchronous coding isn't needed) and Async functions. However, this may just serve to pollute the API even further - why Async and Hopac by default?
3. Pull out Hopac from the standard library and create a separate Http.fs.Hopac library which adds Hopac support. This way, people that want it can take it, but it's not mandatory. However, I have no idea if this is even possible.

Appreciate that you're busy (as am I!) - please don't take this issue as a complaint - I really just want to understand the rationale behind it (which you've explained) and to see what your thoughts are. Perhaps a discussion here can lead to a proposed design which we're all happy with, at which point someone can submit a PR to do it - at this point I think a PR would be premature until we have a valid, workable solution for all concerned.

**Comment by haf** [comment]
I'm fully up to doing all of your suggestions above; they are all great suggestions. I was planning to create a module `HTTP` which has functions like `get` and `post` which can be both async and sync. In fact https://github.com/haf/Http.fs/tree/feature/playing-around is moving towards that. I have the same problem when I script. I'll PR that branch and then you can PR towards that as a way of "commenting".

Here it is https://github.com/haf/Http.fs/pull/111

**Comment by xperiandri** [comment]
Well, this dependency on Hopac causes this library to be unusable with Blazor.
It just crashes as Hopac does not work ☹

**Comment by haf** [comment]
@xperiandri That's not helping. At the very least paste a stacktrace and a description of what is not working. What is Blazor?

I can assure you that Hopac works, though, I've had it in prod for years now.

**Comment by wallymathieu** [comment]
@haf [Blazor](https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor) is .net running on web assembly.
