### ISSUE TITLE
Can't open the .proj file in VS2015

### ISSUE THREAD

**Issue by gusty** [haf/Http.fs#116]
The project appears as unloaded.
If I try to load it I get an error saying:

_The project 'HttpFs.fsproj' could not be opened because opening it would cause a folder to be renamed multiple times in the solution explorer. One such problematic item is '..\paket\files\haf\YoLo\YoLo.fs'. To open this project in Visual Studio, first edit the project file and fix the problem._

In the readme it says that in order to build I should run:

    bundle exec rake

but there is no such file.

**Comment by haf** [comment]
Are you sure it doesn't say `paket-files`? Anyway; the aim here was to download https://github.com/haf/Http.fs/blob/releases/v4.x/paket.lock#L25

When you say "there is no such file", do you mean there is no command "bundle"? Because it then means you have to [install the build tools](https://github.com/Albacore/albacore#getting-started).

I've updated the readme to reflect this as well.
