### ISSUE TITLE
Replace HttpWebRequest usage with HttpClient

### ISSUE THREAD

**Issue by seanamosw** [haf/Http.fs#132]
As mentioned in https://github.com/haf/Http.fs/pull/131#issuecomment-325133706 , in .NET Core, HttpWebRequest is wrapper around HttpClient.

The wrapper itself does not use the correct practices with HttpClient, like re-using a HttpClient, so it has severely degraded performance and will under high load cause socket exceptions.

For a quick observation of the degraded performance, run the integration tests on master.
The .NET 461 Full tests complete in +- 1 sec, the .NET Core tests take +- 12 seconds.

Perhaps some discussion on how to manage the HttpClient and points where the consumer could pass in/use their own one?

**Comment by haf** [comment]
How about we optionally allow a context to be passed in for high performance scenarios?

**Comment by seanamos** [comment]
The intended lifecycle of HttpClient and HttpMessageHandler are quite different from HttpWebRequest. I've been looking at how best to fit that into the current code without too many breaking changes. I don't know if it's possible.

The problem is that both HttpClient and it's associated HttpMessageHandler are meant to be kept as long as possible, often as a singleton, and a lot things that used to live on HttpWebRequest now live on HttpMessageHandler:
 - Cookies
 - Proxy
 - Network Credentials
 - AutomaticDecompression
 - AllowAutoRedirect
 - Connections
 - More...

The current API allows you to set those things per request, which in the HttpClient model would mean either:
 - Race conditions on the HttpMessageHandler if one is used but modified per request.
 - Creating a new MessageHandler/Client per request. Very flexible, but leads back to the performance issue since a new connection will be opened for each request and eventual socket exhaustion.

On the HttpRequestMessage itself, you pretty much only get
  - Content
  - Headers
  - Method
  - Version
  - Of course the url

Dropping the HttpMessageHandler related settings from the API and allowing the consumer to pass in their own HttpClient is one solution, where we default to an internal one if they don't.

```fsharp
module Request

   let createWithClient (clientFactory: Uri -> HttpClient) method uri =
      ...
```
The above can at least be partially applied at the their comp root somewhere where they can use their own HttpMessageHandler.

**Comment by haf** [comment]
The underlying library should not shine through; but we can use strategy to decide which implementation to use. Is HttpClient thread safe? Is MessageHandler?

**Comment by seanamos** [comment]
The methods on HttpClient are thread safe, the properties are not, the same with HttpMessageHandler. 
There are a lot of people going through this pain in .NET. It's not intuitive at all.
https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

I can think of 2 ways to avoid exposing HttpClient directly.
Introduce a builder phase before building the request that allows someone to build the HttpMessageHandler options (cookies, allowautoredirect etc.). Basically building an HttpClient/HttpMessageHandler, but wrapped up by HttpFs.
They can do this at their comp root and it should be reused / partially applied.
Downsides
  - It's tied to how HttpClient works
  - It actually might be abstracting too much, there are custom HttpMessageHandlers that deal with a wide range of things that people would get locked out of:
    * https://github.com/paulcbetts/ModernHttpClient
    * https://github.com/paulcbetts/Fusillade
    * https://github.com/PureKrome/HttpClient.Helpers

The MUCH more complex way is to keep the current public API, but try to match requests with HttpClients/HttpMessageHandlers held internally. Has the downside of lockout again and is very high in effort.

I suppose the final option is just to go all in and do as you've suggested and do F# all the way down to TCP. Pretty high up there on effort!

**Comment by ivpadim** [comment]
This task was completed! thanks to @seanamos
